### ISSUE TITLE
Question to RNA-FM results

### ISSUE THREAD

**Issue by wangleiofficial** [automl/RNAformer#2]
Hi, I want to rerealize the prediction of RNA secondary structure when using RNA-FM and your model, but I am unable to repeat the result (reported in RNA-FM paper). If you can provide the code for secondary structure training, it is very appreciated.

**Comment by JoergFranke** [comment]
Also, we were not able to repeat the results from RNA-FM and therefore reported different values in our paper. We will provide an updated version of the RNAformer soon and then include the training script.
