### ISSUE TITLE
A question about the comparison experiments

### ISSUE THREAD

**Issue by Decem-Y** [automl/RNAformer#3]
Great work, but the experiments do not compare to the comparison experiments for models such as 0.5M, 2M, 8M to add recycling. Can you explain it? Looking forward to your reply.

**Comment by Decem-Y** [comment]
@JoergFranke Very much looking forward to you answering this question.

**Comment by JoergFranke** [comment]
Sorry for the late reply! For the submission, we didn't run the recycling on every scale since a recycling run takes way more time. In the meantime we did and it always improved the performance.

**Comment by Decem-Y** [comment]
Thanks for your reply.
